### PR TITLE
Typo in data-and-programming.Rmd

### PR DESCRIPTION
**Pull request by ksezgin80**
Change "is" to "it"

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
Hi Sezgin, thanks for the pull request. If you'd like to be added to the acknowledgements, please let me know how you'd like your name to appear, (Sezgin Kucukcoban?) and if you'd like me to link to your GitHub or perhaps a LinkedIn.

**Comment by ksezgin80** [comment]
Hi David, thanks for your message. I may have additional pull requests as I
progress, and would love to be added to the acknowledgements. You got my
name right!

Sezgin Kucukcoban - https://www.linkedin.com/in/ksezgin

**Comment by daviddalpiaz** [comment]
Which would you prefer be linked? Your LinkedIn or your GitHub?

**Comment by ksezgin80** [comment]
I prefer LinkedIn. I am a new GitHub user, still learning... There is not
much info there. The link I provided is for my LinkedIn profile. Thanks.

Best regards,
Sezgin Kucukcoban

**Comment by daviddalpiaz** [comment]
Added!

**Comment by ksezgin80** [comment]
Thank you very much!

**Pull request merged**
