### PR TITLE
Update data-and-programming.Rmd

### PR DESCRIPTION
**Pull request by jeffgerlach**
Small typo fixes in Chapter 3

### CODE REVIEW

**Comment by jeffgerlach** [comment]
It appears something may be broken in the Travis build script, unless I didn't configure something appropriately!

**Comment by daviddalpiaz** [comment]
Hmmm. I'm out of town but I'll dig into this more in the next couple days. I think they just updated the pandoc version on Travis. Could be related to that.

**Comment by daviddalpiaz** [comment]
I think I'm right and this is just an issue with the new version of pandoc. I'll try to fix it later today!

**Comment by jeffgerlach** [comment]
The woes of CI! Sounds good, thanks!

**Comment by daviddalpiaz** [comment]
I added you to the acknowledgements. Let me know if you'd like me to change anything about the way it appears.

**Pull request merged**
