### PR TITLE
Fix a typo and update URLs

### PR DESCRIPTION
**Pull request by chadyuu**

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
Thanks! Would you like to appear in the acknowledgements? If so, how would you like your name to appear?

**Comment by chadyuu** [comment]
I appreciate your confirmation!
I would like to show my name and the link to my LinkedIn in the acknowledgment.

Yutaro Nishiyama
https://www.linkedin.com/in/yutaro-nishiyama-a8a895b4/

Thanks.

**Comment by daviddalpiaz** [comment]
Added. Change should be live shortly.

**Comment by chadyuu** [comment]
I found that the following workflow failed. 
https://github.com/daviddalpiaz/appliedstats/runs/6414769484?check_suite_focus=true

Do we need to fix anything?

**Comment by daviddalpiaz** [comment]
No, changes are live. That one failed because another started right after.

**Pull request merged**
