### PR TITLE
Fixes #43 Build leaving behind example-data.csv

### LINKED ISSUE #43: build leave behind a data/example-data.csv file
When you perform a clean build from index.Rmd the file data/example-data.csv shows up as an untracked file.

I would expect things to be clean after a book build.

It looks like there is a very similar and possibly unused file called data/example_data.csv  The only difference is between an underbar and a minus.

### PR DESCRIPTION
**Pull request by rayfix**

### CODE REVIEW

**Comment by coatless** [comment]
This is by design as the generated `example-data.csv` is then made available for students to download. 

See: https://github.com/daviddalpiaz/appliedstats/blob/master/data-and-programming.Rmd#data-frames

Link to data: https://github.com/daviddalpiaz/appliedstats/blob/master/data/example-data.csv

**Comment by rayfix** [comment]
@coatless 

Hello. It is fine that is made available to download but should it show up as version control status (being an untracked file)?  That is why I thought it should be committed.  This way, since it will produce the same content every time git won't give it status.  

In the past example_data.csv was committed.  My guess is that someone changed the filename in the code but didn't commit the new file and remove the old one which is why it now shows up as untracked after a build.

**Comment by rayfix** [comment]
An alternative way to handle it would be to remove it from the repo altogether and add it as a .gitignore entry.

**Comment by daviddalpiaz** [comment]
I think there's a bit of confusion here.

- `example_data.csv` exists as the result of an old build.
- `example-data.csv` needs to, and does exist (but only in the gh-pages branch) given the current build of the book. This is also created as a part of the build process, which is why it only exists on the gh-pages branch.

So I think merging this essentially "fixes" at least the issue of `example_data.csv` needing to be deleted.

**Comment by daviddalpiaz** [comment]
@rayfix I've added you to the acknowledgements. Let me know if you'd like to change anything about the way it appears. Also, I'll look into your other PRs soon. :)

@coatless What's the best way to get rid of all the orphaned files in the`gh-pages` branch? Delete everything from the branch and rebuild?

**Comment by coatless** [comment]
@daviddalpiaz remove the branch and start fresh again.

```bash
# Remove the branch
git push origin --delete gh-pages

# Create a new branch without any content from master
git checkout --orphan gh-pages

# Remove any unstaged files. 
git rm -rf .

# Add .nojekyll to disable jekyll builds
touch .nojekyll
git add .nojekyll

# Take a snapshot
git commit -m "Fresh output branch"

# Push to live
git push origin gh-pages

# Switch back to master
git checkout master
```

Then restart the last CI build or create a new commit on master to re-generate the book.

**Comment by coatless** [comment]
@rayfix spot on. In my hurry, I only noticed the removal of a file. 

In the future consider:

```bash
git mv old_filename new_filename 
```

This allows the diff to be a rename vs. a deletion.

**Comment by rayfix** [comment]
@coatless Got it.  I usually do that but for whatever reason it didn't happen this time.  I will be more careful in the future.
@daviddalpiaz Thanks for the ack! :]

**Pull request merged**
