### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tonymazn**

### CODE REVIEW

**Comment by tonymazn** [comment]
Fix typo

**Comment by daviddalpiaz** [comment]
Hi Tony, thanks for the pull request. If you'd like to be added to the acknowledgements, please let me know how you'd like your name to appear, (Tony Ma?) and if you'd like me to link to your GitHub or perhaps a LinkedIn.

**Comment by tonymazn** [comment]
Sure,  "Tony Ma" is fine, my Linkedln:    "https://www.linkedin.com/in/tony-ma-b978143a/"

Thank you
Tony

**Comment by daviddalpiaz** [comment]
Would you prefer I link to your GitHub or your LinkedIn?

**Comment by tonymazn** [comment]
Professor David,

Please link to Linkedln.

Thank you
Tony

**Comment by daviddalpiaz** [comment]
Added!

**Comment by tonymazn** [comment]
Thank you, professor David.

Tony

**Pull request merged**
