### PR TITLE
Updated the link to the "Base" R cheatsheet

### PR DESCRIPTION
**Pull request by dkrovi2**
The previous link is broken. Found the new link from https://www.rstudio.com/resources/cheatsheets/.

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
I'm looking into why CI is failing, but this looks good.

Would you like to appear in the acknowledgements? If so, how would you like your name to appear? https://daviddalpiaz.github.io/appliedstats/index.html#acknowledgements

**Comment by dkrovi2** [comment]
> Would you like to appear in the acknowledgements? If so, how would you like your name to appear?

Sure :), as "Durga Krovi". thank you.

**Comment by daviddalpiaz** [comment]
Still fighting the CI build, but once I get it sorted, this change and the update to the acknowledges will be live.

**Comment by coatless** [comment]
@dkrovi2 the acknowledgement is now present! Thanks for the PR and your patience.

**Comment by dkrovi2** [comment]
Thank you for the email.

> Would you like to appear in the acknowledgements? If so, how would you like your name to appear?

Sure, as “Durga Krovi“.

Thank you.

Sent with a Spark

**Pull request merged**
