### PR TITLE
Updated the RStudio IDE cheatsheet hyperlink in section 6.5

### PR DESCRIPTION
**Pull request by sidpssp**
Updated the RStudio IDE cheatsheet hyperlink to the new one, as the existing one was no longer active. Also added an additional hyperlink for some additional RStudio related cheatsheets.

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
Looks good! Would you like to appear in the acknowledgements? If so, how would you like your name to appear?

**Comment by sidpssp** [comment]
Sure David. You may add my name as "Siddharth Singh". If you could add a link to my LinkedIn page (https://www.linkedin.com/in/siddharth-singh-87859142/), that would be great.

**Comment by daviddalpiaz** [comment]
Added. Change should be live soon.

**Comment by sidpssp** [comment]
Thanks professor, I can see it now! 👍

**Pull request merged**
