### PR TITLE
Sequence incrementing by a constant value

### PR DESCRIPTION
**Pull request by SahaniGoonetilleke**
Constant can be 0.1 instead of 1 too.

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
I'm wondering if there is just an overall better way to write this sentence. Now that you've suggested an alternative, I definitely don't like what I originally wrote, but I think a bigger change might be needed. Want to take the first pass at a replacement?

**Comment by SahaniGoonetilleke** [comment]
Sure, maybe this...
If we want to create a sequence that isn’t limited to integers with a spacing of 1, but a sequence that can increase/decrease by a constant value at a time ( 0.1 here ), we can use the seq() function.

**Comment by daviddalpiaz** [comment]
How about this?

> To create a sequence that is not limited to consecutive integers, use the `seq()` function to define a sequence by its start, end, and increment.

**Comment by daviddalpiaz** [comment]
I think I like it. Going to merge yours then add my own commit.

**Comment by SahaniGoonetilleke** [comment]
Cool, it looks good!

**Pull request closed without merging**
