### PR TITLE
Updated broken link of Base R cheatsheet

### PR DESCRIPTION
**Pull request by SahaniGoonetilleke**
https://github.com/rstudio/cheatsheets/raw/master/base-r.pdf 
to
https://github.com/rstudio/cheatsheets/blob/main/base-r.pdf

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
Thanks! Would you like to appear in the acknowledgements? If so, how would you like your name to appear?

**Comment by SahaniGoonetilleke** [comment]
Sure, I'd like to appear as Regina Sahani Goonetilleke with my LinkedIn handle [https://www.linkedin.com/in/sahani-goonetilleke/](https://www.linkedin.com/in/sahani-goonetilleke/)
Thanks!

**Comment by daviddalpiaz** [comment]
Added! Update should be live shortly.

**Comment by SahaniGoonetilleke** [comment]
Thanks! Works fine.

**Pull request merged**
