### PR TITLE
Fixes #12 - links to the outside target="_blank"

### LINKED ISSUE #12: Link Targets
Make links to outside domains have target = "_blank"

http://stackoverflow.com/questions/4425198/markdown-target-blank

### PR DESCRIPTION
**Pull request by rayfix**
I used the solution found in the link in the issue.  I tried some other forms such as [Text](http:...){:target="_blank"} but those didn't seem to work.  The following works with a clean build.

I performed this transformation using the following command line:

perl -0777 -pi -e 's/\[([^\]]*)\]\((http[^\)]*)\)/<a href=\"$2\" target=\"_blank\">$1<\/a>/g' *.Rmd \

This transforms links: [Text](http of link) to <a href="http of link" target="blank">Text</a>

I had to back out a couple of changes in index.Rmd because the header is processed by the yaml processor
Also I didn't know how to handle the nested link for the cc license so I backed that out too.

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
Wow. Thanks for this. I'm going to think about it for a few days before merging though.

I've gone back and forth on this a lot. On one hand, your approach is much better from a web-best-practices point of view. (I imagine many users are frustrated any time they click an external link...) However, from an rmarkdown-best-practices point of view, at least personally, I try hard to not mix markdown and html.

What I'd really love is a way to essentially add your code to the build procedure so that this happens automatically for all external links, but everything in the source rmd is still markdown.

**Comment by rayfix** [comment]
Yeah, I really wish there was a way to do it from markdown directly. I searched for it but couldn't find a way.  

One other thought I had is that if you did decide to accept this change, it might be good to add an html class so external links could be styled differently.  It would be pretty trivial to redo as it involves changing the one line of perl.

**Comment by coatless** [comment]
There is a way to do it from _pandoc_ directly using [Extension: `link_attributes`](https://pandoc.org/MANUAL.html#extension-link_attributes), which is enabled by default on the RStudio builds with _RMarkdown_.

You were _very_ close to achieving this. Just needed to drop the `:` inside the `{}`, e.g.

```
[link to PR](https://github.com/daviddalpiaz/appliedstats/pull/42){target="_blank"}
```

This works under all  _three_ formats supported by `bookdown` (html, pdf, epub). I would suggest closing this PR and then redoing the `sed`.

Examples:

test-book
test-book-pdf

**Comment by daviddalpiaz** [comment]
Unreal. Is this something recent in pandoc? I swear I spent a few days on this a year ago and found nothing.

**Comment by coatless** [comment]
The feature has been present in pandoc since at least 2015. I think the issue was the SO post linked in #12 was based on Kramdown's feature set instead of pandoc as the underlying parser.

**Comment by daviddalpiaz** [comment]
I'm going to close this, and update the Issue now that I know the solution. Just need to actually do it...

**Comment by coatless** [comment]
@daviddalpiaz I would encourage @rayfix to re-run the perl regex he had with the aforementioned link syntax. No need to do it by hand.

e.g. 
```
perl -0777 -pi -e 's/[([^]])]((http[^)]))/[$1]($2){target="_blank"}</a>/g' *.Rmd \
```

**Pull request closed without merging**
