### PR TITLE
Updated the RStudio cheatsheet URL in section 6.5

### PR DESCRIPTION
**Pull request by sidpssp**

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
These seems to be grouped and specifically tied to a 2019 conference. Could you instead link to the overview page that overviews all of them? https://www.rstudio.com/resources/cheatsheets/

**Comment by sidpssp** [comment]
Hi David,

How about using the below URL, to directly reach the place where the RStudio IDE cheatsheet starts?
https://www.rstudio.com/resources/cheatsheets/#rstudio-idecheatsheet

If this doesn't look good, then I'll follow your suggestion to link to the top of the cheatsheet page. (https://www.rstudio.com/resources/cheatsheets/)

Thanks,
Sid

**Comment by daviddalpiaz** [comment]
Ah, that actually makes more sense. Maybe both though? That is, add a sentence/link to the landing page as well for "additional" cheat-sheets.

**Comment by sidpssp** [comment]
Sure David. I'll try to come up with a new sentence for the additional cheat-sheets. Once you approve that sentence/link, I'll update  it in the Rmd file.

**Comment by sidpssp** [comment]
`They also have an excellent [RStudio "cheatsheets"](https://www.rstudio.com/resources/cheatsheets/#rstudio-idecheatsheet){target="_blank"} which visually identifies many of the features available in the IDE. You may also explore some additional ["cheatsheets"](https://www.rstudio.com/resources/cheatsheets/){target="_blank"} on their website.`

I've incorporated both the URLs and a new sentence as shown above. Please provide your suggestions, if any improvements are required.

**Comment by daviddalpiaz** [comment]
I think the first instance of cheatsheet should be singular, but other than that, this looks great!

**Comment by sidpssp** [comment]
Got it David. I'll update the verbiage accordingly and push my changes.

**Pull request closed without merging**
