### PR TITLE
Fixed typo in anova.Rmd

### PR DESCRIPTION
**Pull request by nbalepur**
Changed P(Rejct) to P(Reject)

### CODE REVIEW

**Comment by daviddalpiaz** [comment]
Hi `nbalepur`! Can I add you to the acknowledgements section? If so, how would you like your name to appear?

**Comment by nbalepur** [comment]
> Hi `nbalepur`! Can I add you to the acknowledgements section? If so, how would you like your name to appear?

Sure! Can you add me as "Nishant Balepur", and then a link to my GitHub (https://github.com/nbalepur) if possible. Thanks!

**Comment by daviddalpiaz** [comment]
Added! Change should be live in the next hour or so.

**Comment by nbalepur** [comment]
Thank you! Just curious, where can I find the `acknowledgements` section of the textbook?

**Comment by daviddalpiaz** [comment]
https://daviddalpiaz.github.io/appliedstats/index.html#acknowledgements

(The change is not live yet though.)

**Pull request merged**
